[workspace]
resolver = "2"
members = [
  "letrboxd-analysis",
  "letrboxd-benchmarks",
  "letrboxd-cli",
  "letters",
  "word-list",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
